### ISSUE TITLE
Real mode and IPAdapterApplyFaceID node 

### ISSUE THREAD

**Issue by roKadikis** [Chaoses-Ib/ComfyScript#18]
Hi, 

I'm trying to run IPAdapterApplyFaceID node from IPAdapter_plus package in the real mode and get the error below. IPAdapterApply node from the same package works fine. Both those nodes also worked in virtual mode.
Overall this is a very nice tool, any help or hint would be appreciated.

```
from comfy_script.runtime.real import *
load()
from comfy_script.runtime.real.nodes import *


im, mask = LoadImage('test.png')

with Workflow():
    gen_model, gen_clip, gen_vae = CheckpointLoaderSimple('deliberate_v3.safetensors') 
    gen_ipadapter = IPAdapterModelLoader('ip-adapter-faceid-portrait_sd15.bin') 
    clip_vision = CLIPVisionLoader('model.safetensors') 
    insightface = InsightFaceLoader(provider='CUDA')

    adapter_applied_model = IPAdapterApplyFaceID(
        ipadapter=gen_ipadapter, 
        clip_vision=clip_vision, 
        insightface=insightface, 
        image=im, 
        model=gen_model, 
        weight=1, 
        noise=0, 
        weight_type='original', 
        start_at=0, 
        end_at=1, 
        faceid_v2=False, 
        weight_v2=1, 
        unfold_batch=False,
        ) 
```

```
Traceback (most recent call last):
File "/home/ro/test.py", line 16, in <module>
adapter_applied_model = IPAdapterApplyFaceID(
File "/home/ro/ComfyUI/custom_nodes/ComfyScript/src/comfy_script/runtime/real/nodes.py", line 65, in new
obj = orginal_new(cls)
File "/home/ro/ComfyUI/custom_nodes/ComfyScript/src/comfy_script/runtime/real/nodes.py", line 97, in new
outputs = getattr(obj, obj.FUNCTION)(*args, **kwds)
TypeError: IPAdapterApply.apply_ipadapter() missing 2 required positional arguments: 'ipadapter' and 'model'
```

**Comment by Chaoses-Ib** [comment]
It'll be fixed later. A workaround:
```python
adapter_applied_model = IPAdapterApplyFaceID.create().apply_ipadapter(
    ipadapter=gen_ipadapter, 
    clip_vision=clip_vision, 
    insightface=insightface, 
    image=im, 
    model=gen_model, 
    weight=1, 
    noise=0, 
    weight_type='original', 
    start_at=0, 
    end_at=1, 
    faceid_v2=False, 
    weight_v2=1, 
    unfold_batch=False,
    )
```

**Comment by Chaoses-Ib** [comment]
It's fixed now. You can use `git pull` to update. Thanks for your report.
