### ISSUE TITLE
Transpile error with Latent Blend?

### ISSUE THREAD

**Issue by lingondricka2** [Chaoses-Ib/ComfyScript#25]
```
Traceback (most recent call last):
  File "C:\Users\lingo\Desktop\ComfyUI\custom_nodes\ComfyScript\src\comfy_script\nodes\__init__.py", line 94, in chunks
    comfy_script = transpile.WorkflowToScriptTranspiler(workflow).to_script(end_nodes)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lingo\Desktop\ComfyUI\custom_nodes\ComfyScript\src\comfy_script\transpile\__init__.py", line 338, in to_script
    for node in self._topological_generations_ordered_dfs(end_nodes):
  File "C:\Users\lingo\Desktop\ComfyUI\custom_nodes\ComfyScript\src\comfy_script\transpile\__init__.py", line 313, in _topological_generations_ordered_dfs
    yield from visit(v)
  File "C:\Users\lingo\Desktop\ComfyUI\custom_nodes\ComfyScript\src\comfy_script\transpile\__init__.py", line 308, in visit
    yield from visit(node_u)
  File "C:\Users\lingo\Desktop\ComfyUI\custom_nodes\ComfyScript\src\comfy_script\transpile\__init__.py", line 308, in visit
    yield from visit(node_u)
  File "C:\Users\lingo\Desktop\ComfyUI\custom_nodes\ComfyScript\src\comfy_script\transpile\__init__.py", line 308, in visit
    yield from visit(node_u)
  File "C:\Users\lingo\Desktop\ComfyUI\custom_nodes\ComfyScript\src\comfy_script\transpile\__init__.py", line 303, in visit
    inputs = passes.multiplexer_node_input_filter(G.nodes[node], self._widget_values_to_dict(v.type, v.widgets_values))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lingo\Desktop\ComfyUI\custom_nodes\ComfyScript\src\comfy_script\transpile\passes\__init__.py", line 127, in multiplexer_node_input_filter
    if widget_values[k] != value:
       ~~~~~~~~~~~~~^^^
KeyError: 'blend_mode'
Prompt executed in 7.81 seconds
```
[workflow (83).json](https://github.com/Chaoses-Ib/ComfyScript/files/14319536/workflow.83.json)

**Comment by Chaoses-Ib** [comment]
Fixed. It turns out that `blend_mode` was removed in https://github.com/comfyanonymous/ComfyUI/commit/fa962e86c1cdc3bb9dd57ac028fba0e577346983 six months ago.

**Comment by lingondricka2** [comment]
Thank you.
