### ISSUE TITLE
Handling "UI-only" nodes

### ISSUE THREAD

**Issue by ghostsquad** [Chaoses-Ib/ComfyScript#42]
Some nodes it seems are client-only nodes, like `Reroute (rgthree)`. I'm getting this error, and I'm assuming that is why, as it's only javascript, there's no associated Python code with it. How should I handle that?

```
Traceback (most recent call last):
  File "E:\custom_nodes\ComfyScript\src\comfy_script\nodes\__init__.py", line 97, in chunks
    comfy_script = transpile.WorkflowToScriptTranspiler(workflow).to_script(end_nodes)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\custom_nodes\ComfyScript\src\comfy_script\transpile\__init__.py", line 340, in to_script
    c += self._node_to_assign_st(self.G.nodes[node])
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\custom_nodes\ComfyScript\src\comfy_script\transpile\__init__.py", line 193, in _node_to_assign_st
    args = self._keyword_args_to_positional(v.type, args_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\custom_nodes\ComfyScript\src\comfy_script\transpile\__init__.py", line 122, in _keyword_args_to_positional
    input_types = self._get_input_types(node_type)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\custom_nodes\ComfyScript\src\comfy_script\transpile\__init__.py", line 81, in _get_input_types
    return self.nodes_info[node_type]['input']
           ~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'Reroute (rgthree)'
```

**Comment by Chaoses-Ib** [comment]
It's now fixed. Thanks for your report.

If you encounter other UI-only nodes in the future, you can workaround this problem by exporting the API format workflow and transpiling it. I've also added this in the exception message:

![image](https://github.com/Chaoses-Ib/ComfyScript/assets/50246090/28a041b3-9cb8-4e83-88aa-097ff334432b)

**Comment by ghostsquad** [comment]
I've updated, and now I'm getting this:

```
Traceback (most recent call last):
  File "E:\custom_nodes\ComfyScript\src\comfy_script\nodes\__init__.py", line 97, in chunks
    comfy_script = transpile.WorkflowToScriptTranspiler(workflow).to_script(end_nodes)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\custom_nodes\ComfyScript\src\comfy_script\transpile\__init__.py", line 344, in to_script
    c += self._node_to_assign_st(self.G.nodes[node])
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\custom_nodes\ComfyScript\src\comfy_script\transpile\__init__.py", line 191, in _node_to_assign_st
    'exp': output_ids[u_slot],
           ~~~~~~~~~~^^^^^^^^
KeyError: 3
```

**Comment by Chaoses-Ib** [comment]
Can you share the workflow? I've tested workflow with `Reroute (rgthree)` and saw no errors.

![image](https://github.com/Chaoses-Ib/ComfyScript/assets/50246090/fd7cd5ee-fedf-44d0-93f1-735ab61ec729)

**Comment by Chaoses-Ib** [comment]
I've added a fallback mechanism to workaround this sort of issues. In case a node cannot be found, the transpiler hook will try to transpile the API format workflow again.

![image](https://github.com/Chaoses-Ib/ComfyScript/assets/50246090/ab6a5fe9-ff54-4e26-b3c9-831e3a624afc)

(`Reroute (rgthree)` support is removed for demo)

**Comment by ghostsquad** [comment]
here's my complex workflow, which is the reason I'm looking to go to ComfyScript. I'm running into way too many UI limitations, and it's hard to grok what is different between generations (when I turn knobs, adjust parameters, etc.). 

[comfyscript-troubleshooting.json](https://github.com/user-attachments/files/15840280/comfyscript-troubleshooting.json)

**Comment by Chaoses-Ib** [comment]
It's indeed a complex workflow... Can you share the workflow in API format too? There are too many missing nodes on my side and I can't export it in APi format correctly. The "Save (API Format)" will be shown after turning on "Enable Dev mode Options" in the settings of the web UI.

**Comment by ghostsquad** [comment]
[workflow_api.json](https://github.com/user-attachments/files/15844701/workflow_api.json)

as requested

**Comment by ghostsquad** [comment]
Here's another one: `Node not found: Fast Groups Muter (rgthree)`

**Comment by ghostsquad** [comment]
Instead of throwing this error, is there a way to do the transpilation programmatically?

**Comment by Chaoses-Ib** [comment]
> Here's another one: Node not found: `Fast Groups Muter (rgthree)`

Is there only this error? I've already added a mechanism that will use the API format (which has no UI-only nodes) after the web UI format fails.

> Instead of throwing this error, is there a way to do the transpilation programmatically?

You can specify the node where the transpilation starts, e.g. `WorkflowToScriptTranspiler.to_script([123])`, but that's all.

**Comment by ghostsquad** [comment]
Oh, maybe I just need to update again.

**Comment by Chaoses-Ib** [comment]
The fallback only exists in the web UI SaveImage hook before. In case you are using the metadata viewer, I've also added fallback to it now.

**Comment by Chaoses-Ib** [comment]
#77 reported a similar problem. And because the used UE Nodes don't support API format (#78), API format fallback also failed. Such case probably can only be handled by adding support for specific UI-only nodes, or adding some complex tracing hacks to record the actually executed workflow...

**Comment by Chaoses-Ib** [comment]
Documented at https://github.com/Chaoses-Ib/ComfyScript/blob/main/docs/Nodes/Compatibility.md.
