### ISSUE TITLE
use comfyscript on modal return "ValueError: Host '127.0.0.1:8199' cannot contain ':'"

### ISSUE THREAD

**Issue by binarytahr** [Chaoses-Ib/ComfyScript#73]
i write my modal script according to your example script: [ComfyScript/examples/modal.py at main · Chaoses-Ib/ComfyScript](https://github.com/Chaoses-Ib/ComfyScript/blob/main/examples/modal.py). modal always return error before or after comfyscript load(), may i ask for some help or advice?

my code snippets:
```python
@app.cls(
	allow_concurrent_inputs=10,
	concurrency_limit=1,
	container_idle_timeout=30,
	timeout=300,
	gpu="T4",
)
class comfyui_flux:
	@modal.build()
	def build(self):
		print('building container...')

	@modal.enter()
	def enter(self):
		print('entering container...')
		from comfy_script.runtime import load, ComfyUIArgs
		# load()
		# load(comfyui='http://127.0.0.1:8199')
		load(args=ComfyUIArgs('--listen', '127.0.0.1', '--port', '8199'))

	@modal.exit()
	def exit(self):
		print('exiting container...')

	@modal.method()
	def inference(self, prompt, image_size, step, seed, guidance, sampler='euler', scheduler='simple', denoise=1):
		print('start inference...')
		from comfy_script.runtime import Workflow
		from comfy_script.runtime.nodes import UnetLoaderGGUF, DualCLIPLoaderGGUF, VAELoader, EmptyLatentImage, CLIPTextEncodeFlux, ConditioningZeroOut, KSampler, VAEDecode, SaveImage, LoraLoaderModelOnly
		with Workflow(queue=True, wait=True):
```

error in modal app logs:
```log
Ib Custom Nodes: Loaded
ComfyScript: Loaded

Import times for custom nodes:
   0.0 seconds: /root/comfy/ComfyUI/custom_nodes/websocket_image_save.py
   0.0 seconds: /root/comfy/ComfyUI/custom_nodes/ComfyUI-GGUF
   0.3 seconds: /root/comfy/ComfyUI/custom_nodes/ComfyUI-Manager
   1.9 seconds: /root/comfy/ComfyUI/custom_nodes/ComfyScript

Starting server

To see the GUI go to: http://127.0.0.1:8199
Nodes: 225
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 473, in _handle
    match_info = await self._router.resolve(request)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_urldispatcher.py", line 1010, in resolve
    match_dict, allowed = await resource.resolve(request)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_urldispatcher.py", line 755, in resolve
    not request.url.raw_path.startswith(self._prefix2)
        ^^^^^^^^^^^
  File "aiohttp/_helpers.pyx", line 26, in aiohttp._helpers.reify.__get__
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_request.py", line 437, in url
    url = URL.build(scheme=self.scheme, host=self.host)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yarl/_url.py", line 380, in build
    netloc = cls._make_netloc(
             ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yarl/_url.py", line 1052, in _make_netloc
    ret = cls._encode_host(host)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yarl/_url.py", line 1033, in _encode_host
    _host_validate(host)
  File "/usr/local/lib/python3.11/site-packages/yarl/_url.py", line 1602, in _host_validate
    raise ValueError(
ValueError: Host '127.0.0.1:8199' cannot contain ':' (at position 9)
ComfyScript: Failed to watch, will retry in 5 seconds: 500, message='Invalid response status', url=URL('http://127.0.0.1:8199/ws?clientId=acb2c98c-3a8e-485d-9f72-f57dec0026bb')
Traceback (most recent call last):
  File "/root/comfy/ComfyUI/custom_nodes/ComfyScript/src/comfy_script/runtime/__init__.py", line 488, in _watch
    async with session.ws_connect(f'{client.client.base_url}ws', params={'clientId': _client_id}) as ws:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 795, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 500, message='Invalid response status', url=URL('http://127.0.0.1:8199/ws?clientId=acb2c98c-3a8e-485d-9f72-f57dec0026bb')
```

**Comment by Chaoses-Ib** [comment]
Does `load()` without args also return errors?

**Comment by Chaoses-Ib** [comment]
`result` 是个任务，要先 wait 等它完成，再 wait 来获取图片 list：
```python
from PIL import Image

images: list[Image.Image] = result.wait().wait()
```
这部分文档在 https://github.com/Chaoses-Ib/ComfyScript/blob/main/docs/Images/README.md#saving 。这个写法确实有点绕，后面可能会把惰性获取图片去掉来简化成 wait 一次，应该也没多少场景用得到。

Modal 支持不支持序列化 PIL.Image.Image 我不确定，如果不支持的话还要自己序列化下，可以用 `_repr_png_()` 转成 bytes。

**Comment by Chaoses-Ib** [comment]
@twobob Are you affected by this? aiohttp has released a fixed version one day after the yarl release. To trigger this error one must use a new yarl version and an old aiohttp version tpgether. I thought it's unlikely anyone would encounter this case so I closed the issue without changing `pyproject.toml`.

**Comment by twobob** [comment]
no. I am fine thanks but that error. The exact error is the only result on google for The upstream Comfy UI failing to load for the exact same reason. This only happens on misconfigured machines. I apologise for the noise but thought just adding a solution would be better than you fending off multiple "HOW DO I FIX THIS IN  _n_ " requests.
