### ISSUE TITLE
AssertionError with VHSVideoCombine node

### ISSUE THREAD

**Issue by DaWolfey** [Chaoses-Ib/ComfyScript#80]
I am trying to use a simple workflow to load a video file, pass it through RIFE, and output it back to a video, preserving the audio.

The workflow works correctly in ComfyUI, and the script is what ComfyScript outputs, though for some reason it comments out the VHSVideoCombine line, which I have put back in.

The script:

```
from comfy_script.runtime import *
load()

from comfy_script.runtime.nodes import *
with Workflow():
    image, _, audio, video_info = VHSLoadVideoPath(r'D:\My Video\Privacy\Clip-155.mov', 30, 'Disabled', 512, 512, 0, 0, 1, None, None)
    source_fps, _, _, _, _, _, _, _, _, _ = VHSVideoInfo(video_info)
    image = RifeVfi('rife49.pth', image, 10, 2, True, True, 2, None)
    video = VHSVideoCombine(image, source_fps, 0, 'RIFE49', 'video/h264-mp4', False, True, audio, None, None)
```

Which results in:

```
Traceback (most recent call last):
  File "D:\AI\Comfy\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)


  File "D:\AI\Comfy\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    

  File "D:\AI\Comfy\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\AI\Comfy\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "D:\AI\Comfy\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 402, in combine_video
    video_format = apply_format_widgets(format_ext, kwargs)

  File "D:\AI\Comfy\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 88, in apply_format_widgets
    assert(w[0][0] in kwargs)

AssertionError
```

**Comment by Chaoses-Ib** [comment]
You may need to add some args manually, see https://github.com/Chaoses-Ib/ComfyScript/issues/22#issuecomment-1937053248

**Comment by DaWolfey** [comment]
Reading h264-mp4.json in custom_nodes\ComfyUI-VideoHelperSuite\video_formats seems to show that I need to add pix_fmt, crf and save_metadata, so:

```
video = VHSVideoCombine(image, source_fps, 0, 'RIFE49', 'video/h264-mp4', False, True, audio, None, None, pix_fmt = 'yuv420p', crf=19, save_metadata = True)
```

but this gives me a new error which happens before it even connects to comfyui:

```
Traceback (most recent call last):
  File "D:\AI\Comfy\custom_nodes\ComfyScript\interpolate.py", line 5, in <module>
    with Workflow():
  File "D:\AI\Comfy\custom_nodes\ComfyScript\src\comfy_script\runtime\__init__.py", line 1048, in __exit__
    asyncio.run(self._exit(source, exc_type, exc_value, traceback))
  File "D:\AI\ComfyUI\.venv\Lib\site-packages\nest_asyncio.py", line 30, in run
    return loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI\.venv\Lib\site-packages\nest_asyncio.py", line 98, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\tasks.py", line 277, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "D:\AI\Comfy\custom_nodes\ComfyScript\src\comfy_script\runtime\__init__.py", line 1034, in _exit
    if await self._queue(source):
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\Comfy\custom_nodes\ComfyScript\src\comfy_script\runtime\__init__.py", line 1012, in _queue
    self.task = await queue._put(self, source)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\Comfy\custom_nodes\ComfyScript\src\comfy_script\runtime\__init__.py", line 655, in _put
    prompt, id = workflow._get_prompt_and_id()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\Comfy\custom_nodes\ComfyScript\src\comfy_script\runtime\__init__.py", line 996, in _get_prompt_and_id
    return data._get_outputs_prompt_and_id(self._outputs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\Comfy\custom_nodes\ComfyScript\src\comfy_script\runtime\data\__init__.py", line 112, in _get_outputs_prompt_and_id
    return outputs[0]._get_prompt_and_id()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\Comfy\custom_nodes\ComfyScript\src\comfy_script\runtime\data\__init__.py", line 51, in _get_prompt_and_id
    self._update_prompt(prompt, id)
  File "D:\AI\Comfy\custom_nodes\ComfyScript\src\comfy_script\runtime\data\__init__.py", line 75, in _update_prompt
    if factory.is_bool_enum(input_type):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\Comfy\custom_nodes\ComfyScript\src\comfy_script\runtime\factory.py", line 23, in is_bool_enum
    if len(enum) != 2:
       ^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
```

**Comment by Chaoses-Ib** [comment]
Should be fixed now. You can run `git pull` to update.

**Comment by DaWolfey** [comment]
That has fixed it - thank you for the fast response!
