### ISSUE TITLE
AttributeError: 'types.SimpleNamespace' object has no attribute 'links'

### ISSUE THREAD

**Issue by 6sixteen** [Chaoses-Ib/ComfyScript#84]
Traceback (most recent call last):
  File "F:\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\ComfyScript\src\comfy_script\nodes\__init__.py", line 100, in chunks
    comfy_script = transpile.WorkflowToScriptTranspiler(workflow).to_script(end_nodes)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\ComfyScript\src\comfy_script\transpile\__init__.py", line 391, in to_script
    c += self._node_to_assign_st(self.G.nodes[node])
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\ComfyScript\src\comfy_script\transpile\__init__.py", line 243, in _node_to_assign_st
    if output.links is not None and len(output.links) > 0:
       ^^^^^^^^^^^^
AttributeError: 'types.SimpleNamespace' object has no attribute 'links'Traceback (most recent call last):
  File "F:\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\ComfyScript\src\comfy_script\nodes\__init__.py", line 100, in chunks
    comfy_script = transpile.WorkflowToScriptTranspiler(workflow).to_script(end_nodes)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\ComfyScript\src\comfy_script\transpile\__init__.py", line 391, in to_script
    c += self._node_to_assign_st(self.G.nodes[node])
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\ComfyScript\src\comfy_script\transpile\__init__.py", line 243, in _node_to_assign_st
    if output.links is not None and len(output.links) > 0:
       ^^^^^^^^^^^^
AttributeError: 'types.SimpleNamespace' object has no attribute 'links'

**Comment by Chaoses-Ib** [comment]
Can you provide the workflow that triggered this?
